### ISSUE TITLE
Phoscon: Adding Ikea switch never shows in the GUI

### ISSUE THREAD

**Issue by criemen** [dresden-elektronik/phoscon-app-beta#81] opened 2020-05-31 20:45 UTC
Hi,

when adding an Ikea TRÅDFRI remote control, the popup that initiates pairing of the switch never suceeds, it always ends with "Failed to connect".
However, in the background the switch *does* get added and works.

**Comment by Cornelius-Riemenschneider** [comment] 2020-06-05 11:21
I connected some more switches from Ikea, and for those that paired, the dialogue also worked.
However yesterday, after pairing the first switch, which worked quick, two more switches did not pair at all (I tried 5+ times, with 3cm distance to the ConBee II stick).
However, today, the pairing worked flawlessly.

**Comment by YKO-de** [comment] 2020-09-30 09:31
I would close the issue for now. If the issue is still topical, please open a new one. Please indicate the FW version and deCONZ version in the description.

**Closed by YKO-de** 2020-09-30 09:31 UTC
