### ISSUE TITLE
Philips Hue dimmer switch not working reliable

### ISSUE THREAD

**Issue by Gerben321** [dresden-elektronik/phoscon-app-beta#78] opened 2020-05-31 13:10 UTC
So first of all, nice software so far. I've been using it since yesterday and I've moved over all my Aqara stuff, and so far 7 Hue lights (the other ones are a PITA to re-pair because of their enclosure...).

Seems to be working fine so far, but my Hue dimmer switch isn't really working like it used to I think. First of all, before I could press the dim up/down buttons once to make a very small dim change. Now a single press turns the lights on or off, that seems odd and not logical? Because that's what the big on/off buttons are for in my opinion.

Secondly, when I long press the dim up/down buttons my lights are unevenly dimming! 2/4 lights go up, but the other 2 stay very dimmed. How is that possible when they're identical bulbs and used to work perfectly before this? They're E27 simple dimming Ikea lights. Also, the on button has to be clicked 2 of 3 times sometimes before it registers the click. I almost never had this with the Hue hub. My links all seem to be healthy, and even have multiple lines to the lights and dimmer, so I would say the signals should be going through fine?

This is how my map looks right now. Everything is green, that's good right? Should I give it some time to all calm down and connect? Otherwise I have to keep my Hue hub for the dimmer and those 4 lights I'm afraid!
![afbeelding](https://user-images.githubusercontent.com/24865452/83353144-c66d8980-a350-11ea-8596-2c3da944c72d.png)

**Comment by YKO-de** [comment] 2020-09-30 09:24
Since nothing more has happened here for a long time I would close the issue now. If the issue is still topical, please open a new one.

**Closed by YKO-de** 2020-09-30 09:24 UTC
