### ISSUE TITLE
System renames2 Xiaomi temperature sensors after adding a Xiaomi door sensor

### ISSUE THREAD

**Issue by Doreinie** [dresden-elektronik/phoscon-app-beta#219] opened 2020-10-01 14:30 UTC
This happend now for a 2nd time. Today I added a new Xiaomi door sensor to the Phoscon.
The addition of the new door sensor was easy. However, suddenly 2 Xiaomi temperature sensors were renamed in Phoscon with device 37. (Yes, same name).
When wanting to rename one temp sensor back to "Temperatur Sensor Schlafzimmer" the app does not allow so. Error message is that there is already one device named this was. However this is 100% not the case. I have not name it with a "1" in addition.
The 2nd Sensor I can rename to same as before with "Temperatur Sensor Bad groß". No problem with that one.
Now I decided for a reboot of the Rasp.Pi 4b.
However, reboot does not help to make Phoscon "forget" that is does not have already a named "Temperatur Sensor Schlafzimmer"
![image](https://user-images.githubusercontent.com/57943613/94822709-40974300-0403-11eb-89e0-d922a39870d3.png)

What do I need to do to rename the device the way I want to name it. There is 100% no other device called this name!

**Comment by Doreinie** [comment] 2020-10-05 20:34
With help from discord I found out how to rename the sensor. 
Interesting is still that when adding new Xiaomi sensors that some sensors are being renamed.

**Comment by Doreinie** [comment] 2020-10-18 18:36
I hear that others do have same renaming problem when adding Xiaomi products. Is that further investigated?

**Comment by YKO-de** [comment] 2020-10-20 07:34
I'm looking at it. I thought it was fixed in between.

**Comment by moobid** [comment] 2020-10-23 20:08
I am also affected by this. In contrast to @Doreinie's case my Sensors / Switches rename themselves without any adding of a new sensor by me.
![image](https://user-images.githubusercontent.com/5289345/97049321-d5610c80-157b-11eb-8e34-96dbf8e447f5.png)
The Aqara Door Sensor, which was named "OpenClose1" before was changed to "TempWohnzimmer". Note that there is the correct "TempWohnzimmer" sensor which is indeed the Aqara Temperature Sensor.
As I said, this name change happened without any action by me.

I also have Aqara Switches wich also get renamed sometimes. But OSRAM Plugs, which are in Lights never got renamed so far.

I am using Phoscon Version 2.05.84 / 14.9.2020 on a Raspberry Pi 2B with Conbee Stick 2

**Comment by Doreinie** [comment] 2020-10-25 21:28
Today I added an additional door contact.
Again the in Phoscon interface it changes the name of 2 top in line Temperature sensors to the name of the "OpenClose47" just added Xiaomi door sensor.
Then when renaming the last sensor the top 2 sensor take the name of the last changed.


I have compiled the story in a word doc or pdf but it seem I canot upload the file. 
Hence, providing a google drive link for people to laugh about what is happening....
https://drive.google.com/file/d/1EspNWE5xqQxyj7el5hfZrba-WzN-7Hlx/view?usp=sharing

**Comment by Doreinie** [comment] 2020-10-25 21:29
> I'm looking at it. I thought it was fixed in between.

not fixed. just got this odd thing again today

**Comment by moobid** [comment] 2020-11-05 10:24
I just added a new Aqara Temperature Sensor. Shortly after that I could observe how the new and another old Temperature Sensor both changed names rapidly on the Sensors page.
Both names changed like every half second, after some time the 'magic' renaming stopped. The names were: 'Temperature 186', 'Pressure 188', and some others....

**Comment by Doreinie** [comment] 2020-11-05 10:34
@YKO-de Have you been able to progresss the checking you wrote about? It seems always to happen when adding new Xiaomi sensors. As well always the same (top 2 listed) sensors will rename when adding a new sensor.

**Comment by moobid** [comment] 2020-11-05 10:50
Fyi: my old sensor which was renamed was on position 2 in the list of sensors

**Comment by moobid** [comment] 2020-12-14 13:59
This issue is still occuring every time I add a new device. The last device I added was a Eurotronic Thermostat

**Comment by manup** [comment] 2020-12-14 14:27
I can confirmed this, need to make some more tests I'm not sure yet if it happens in the REST-API or the Phoscon App.

**Comment by BenF1sh** [comment] 2020-12-22 14:51
Same here... And because I have a bunch oft the same AQARA Sensors (PIR and window contacts) I'm not able to see which one I'm dealing with after some ghosty renamed themselves (without walking through the whole house and/or opening windows like a fool...). Showing the sensor's UID or S/N in the GUI woukd be nice.

**Comment by moobid** [comment] 2021-01-27 17:13
I have switched from a Raspberry Pi2B to Raspberry Pi4B 4GB.
I have set up everything from scatch and havn't experienced this bug again on my new system.

**Closed** 2021-05-17 10:14 UTC
