### ISSUE TITLE
Group setting and scene issue (with Tradfri)

### ISSUE THREAD

**Issue by realwax** [dresden-elektronik/phoscon-app-beta#52] opened 2019-03-28 11:11 UTC
When using the phoscon app beta there are issues I encountered with Tradfri lights and saving individual scenes. The scene itself gets stored but with wrong parameters. It can only be fixed in the old app, 
Reproduce:

Create a group, put lights in, set the lights individually, then use the group modification and set them equally, store it as scene. change it to different setting, maybe with individual settings on some lights, store again a scene. Set the scene active and change back to the other. You will notice some lights have not been stored properly. Thsi can be seen in the old app and corrected there.

**Comment by StephanStS** [comment] 2020-05-30 09:24
@realwax: Hello Wolfgang, 
was this issue with the "old" Phoscon web app ("Wireless light control" from 2016) or with the actual UI ("Phoscon Web App", pwa)?
The referenced https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1390 seems to describe it at the old web app.

@YKO-de: As I understand the old web app is not supported any more. If this issue is regarded to this app, it could be closed with label "wontfix".

**Comment by realwax** [comment] 2020-05-31 09:51
@StephanStS it was produced by the new web app and only to be solved by correcting and modifying single light parameters of belonging group lights before storing the scene again. It can be corrected with the new and old gui. Bottom line is you have to save and restore the scene a couple of times until is is ok. It s caused by group modifying and saving a scene rather than modifying each single light of its own. Maybe this is tradfri specific with phoscon or not.

**Comment by StephanStS** [comment] 2020-06-06 18:24
@YKO-de: If this can be confirmed as a bug from your side, you could mark this with the label *bug*. After a released bugfix you could close this issue.

**Comment by realwax** [comment] 2020-06-06 20:04
@YKO-de @StephanStS 
I did some retesting with my Conbee I on latest FW and 2.05.77 with my Tradfri E14 WS opal 400lm on IKEA latest FW 2.3.050.

Most issues are gone but a new one appeared. In general usability is a little bit slower than on the 1.x FW. Maybe due to the new Zigbee version.

Changes:

The old WEBIF wireless light control can't be used anymore to modify bulb parameters. Bulbs do not react.

The new issue:

Create a group of light. e.g 4 bulbs. Create a scene with all 4 on and on certain setting. Create another scene, switch two bulb off, modify parameters - store. 
Recall the first scene illuminating all 4 - recall the second scene that is supposed to illuminate only 2 bulb. In this case as they are turned on - 2 bulbs should be turned off - this is the issue - they don't.
If you call the scene with bulbs off - no problem but as soon they are turned on due to a scene recall they do not turn off again if not needed in another scene in the belonging group.

Thank your fix/help/solution and foremost time :)

**Comment by morfei1** [comment] 2020-06-16 14:55
After you use a scene, are the actual color and brightness of the lights in that group set correctly? I know the sliders are not in phoscon, because I have the same problem. What about, if you press again the same scene button, are the sliders set correctly?

**Comment by realwax** [comment] 2020-06-17 10:07
See the discussion: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/2892

It seems like it's an IKEA firmware issue. If you set it via API you have exactly the same behaviour. 
The IKEA firmware >1.x seems to have issues with group settings stored on the bulb. In versions =1.x not used group members in a certain scene were turned off. In FW v =2.x it does not work anymore. This is a standard zigbee functionality that  seems to be broken by ikea. Maybe they mitigate on their own bridge which would be proprietary approach. (and not good) 

It would be good to address IKEA fw dev with this. Does anyone have a contact email? I contacted ikea via standard homepage. Let's see.....

For now we could close this here. Though I like to have some focus on this as it is a deal breaker for using Deconz with Ikea lights! 

...u decide...

**Comment by realwax** [comment] 2020-06-19 19:09
Please lift it up.... https://www.reddit.com/r/tradfri/comments/haqrf5/tradfri_firmware_issue_in_between_major_version/ ;)

**Comment by YKO-de** [comment] 2020-09-30 09:23
Since nothing more has happened here for a long time I would close the issue now. If the issue is still topical, please open a new one.

**Closed by YKO-de** 2020-09-30 09:23 UTC
