### ISSUE TITLE
[Device Request] Lidl/Silvercrest Remote control

### ISSUE THREAD

**Issue by eric-zimmer** [dresden-elektronik/phoscon-app-beta#284] opened 2020-12-28 15:27 UTC
As in this topic
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3829

I would like to use the remote within the phoscon app.

**Comment by davidkrass** [comment] 2021-01-05 06:32
Yes, that would be great. I have 4 of these flying around.

**Comment by snapcatcher** [comment] 2021-01-07 16:25
Yes i woud also love it, if support for that remote would be added :)

**Comment by YKO-de** [comment] 2021-01-11 13:10
Noted. ;)

**Comment by lucky2k12** [comment] 2021-06-02 20:00
Amy News? @YKO-de

**Comment by SEK-DE** [comment] 2021-06-03 13:41
Duplicate of #315 
Closed

**Closed** 2021-06-03 13:41 UTC
