### ISSUE TITLE
Sonoff SNZB-01 switch not available for linking to a group

### ISSUE THREAD

**Issue by senilio** [dresden-elektronik/phoscon-app-beta#299] opened 2021-01-10 15:50 UTC
I have multiple SNZB-01 switches in my zigbee network, all added via Phoscon. They are not showing in the list of "linkable" switches when I go to "Main page" - "Group" - "Switch editor" - "Link switch".

Would it be possible to allow this switch to be used for actions in Phoscon? It supports single, double and long press.

Thanks

**Comment by YKO-de** [comment] 2021-01-11 12:15
There is no individual image for this switch yet. Therefore it is not yet listed in the Switch Editor. But I will try to integrate it by means of a generic image. Thanks for the hint.

**Comment by bmalynovytch** [comment] 2021-02-27 18:23
Any idea when that will be done ?
Got the exact same issue.

**Comment by YKO-de** [comment] 2021-03-08 12:51
It should already work via phoscon.de/pwabeta. You are welcome to test it. The update of the stable will take some time due to a restructuring.

**Comment by bmalynovytch** [comment] 2021-03-11 08:04
> It should already work via phoscon.de/pwabeta. You are welcome to test it. The update of the stable will take some time due to a restructuring.

Oh thank you for the update, I'll give it a look ASAP and update here !

**Comment by bmalynovytch** [comment] 2021-03-19 17:40
Firmware : 26680700
Version : 2.10.03 / 14/03/2021

Hmm ... Sorry but still no luck.
They are visible in the "Devices / Switch" page but not visible in the "Switch editor"

**Comment by bmalynovytch** [comment] 2021-05-04 12:28
No update about this issue ?

**Comment by SEK-DE** [comment] 2021-06-02 13:28
Wierd. Can you send me the the log from API-information (under Help) from the web app beta: http://phoscon.de/pwabeta

**Comment by marvin-SL** [comment] 2021-06-16 13:13
Same for me with the last update and pwabeta.

Here's the log




{
    "config": {
        "UTC": "2021-06-16T12:55:51",
        "announceinterval": 45,
        "announceurl": "https://phoscon.de/discover",
        "apiversion": "2.11.05",
        "bridgeid": "00212EFFFF0739CE",
        "datastoreversion": "93",
        "devicename": "ConBee II",
        "dhcp": true,
        "disablePermitJoinAutoOff": false,
        "discovery": true,
        "factorynew": false,
        "fwneedupdate": false,
        "fwupdatestate": "idle",
        "fwversion": "0x26660700",
        "gateway": "192.168.1.1",
        "groupdelay": 50,
        "homebridge": "not-available",
        "ipaddress": "192.168.1.39",
        "lightlastseeninterval": 60,
        "linkbutton": false,
        "localtime": "2021-06-16T14:55:51",
        "mac": "84:39:c0:0b:17:f3",
        "modelid": "deCONZ",
        "name": "Phoscon-GW",
        "netmask": "255.255.255.0",
        "networkopenduration": 180,
        "otauactive": false,
        "otaustate": "off",
        "panid": 31043,
        "permitjoin": 0,
        "permitjoinfull": 0,
        "port": 8080,
        "portalservices": false,
        "proxyaddress": "none",
        "proxyport": 0,
        "replacesbridgeid": null,
        "rfconnected": true,
        "runmode": "normal",
        "starterkitid": "",
        "swcommit": "ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0",
        "swupdate": {
            "notify": false,
            "text": "",
            "updatestate": 0,
            "url": "",
            "version": "2.11.05"
        },
        "swupdate2": {
            "autoinstall": {
                "on": false,
                "updatetime": ""
            },
            "bridge": {
                "lastinstall": "2021-05-17T16:24:11",
                "state": "noupdates"
            },
            "checkforupdate": false,
            "lastchange": "",
            "state": "noupdates"
        },
        "swversion": "2.11.05",
        "system": "other",
        "timeformat": "12h",
        "timezone": null,
        "updatechannel": "stable",
        "uuid": "c4f50f6c-51b4-4ddf-923d-d84222cfe01b",
        "websocketnotifyall": true,
        "websocketport": 443,
        "whitelist": {
            "1CD3CBEA04": {
                "create date": "2021-06-13T20:32:58",
                "last use date": "2021-06-15T21:46:41",
                "name": "Phoscon#B360x273"
            },
            "21A88E4457": {
                "create date": "2021-06-16T12:22:29",
                "last use date": "2021-06-16T12:52:31",
                "name": "Phoscon#B1280x597"
            },
            "4DBDCA536B": {
                "create date": "2021-06-15T10:56:12",
                "last use date": "2021-06-15T10:56:53",
                "name": "Phoscon#B360x315"
            },
            "5D5F40BCF6": {
                "create date": "2021-06-05T14:54:38",
                "last use date": "2021-06-05T14:54:41",
                "name": "Phoscon#B1366x645"
            },
            "98E23C2A29": {
                "create date": "2021-06-16T12:54:17",
                "last use date": "2021-06-16T12:55:51",
                "name": "Phoscon#B1280x597"
            }
        },
        "wifi": "not-available",
        "wifiavailable": [],
        "wifichannel": "1",
        "wificlientname": null,
        "wifiip": "192.168.8.1",
        "wifimgmt": 0,
        "wifiname": null,
        "wifitype": "accesspoint",
        "zigbeechannel": 15
    },
    "groups": {
        "2": {
            "action": {
                "alert": "none",
                "bri": 127,
                "colormode": "hs",
                "ct": 0,
                "effect": "none",
                "hue": 0,
                "on": true,
                "sat": 127,
                "scene": "1",
                "xy": [
                    0,
                    0
                ]
            },
            "devicemembership": [],
            "etag": "9178b312ecaf3b866e7931bf7ccefa71",
            "hidden": false,
            "id": "2",
            "lights": [
                "2"
            ],
            "lightsequence": [],
            "multideviceids": [],
            "name": "Salon",
            "scenes": [
                {
                    "id": "1",
                    "lightcount": 1,
                    "name": "Scène Lumière Salon",
                    "transitiontime": 0
                }
            ],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "LightGroup"
        },
        "4": {
            "action": {
                "alert": "none",
                "bri": 127,
                "colormode": "hs",
                "ct": 0,
                "effect": "none",
                "hue": 0,
                "on": false,
                "sat": 127,
                "scene": null,
                "xy": [
                    0,
                    0
                ]
            },
            "devicemembership": [
                "9"
            ],
            "etag": "5cea63e7094e97f13aa76dae6ad9f29b",
            "hidden": false,
            "id": "4",
            "lights": [],
            "lightsequence": [],
            "multideviceids": [],
            "name": "WB01 9",
            "scenes": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "LightGroup",
            "uniqueid": "00:12:4b:00:22:ee:43:58"
        }
    },
    "lights": {
        "1": {
            "etag": "0ccea6c41b542d107d40952d19ca7e59",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2021-06-16T12:54Z",
            "manufacturername": "dresden elektronik",
            "modelid": "ConBee II",
            "name": "Configuration tool 1",
            "state": {
                "reachable": true
            },
            "swversion": "0x26580700",
            "type": "Configuration tool",
            "uniqueid": "00:21:2e:ff:ff:07:39:ce-01"
        },
        "2": {
            "etag": "949e7c6abc3d7449c144c65de793da3a",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "SONOFF",
            "modelid": "01MINIZB",
            "name": "Lumière salon",
            "state": {
                "alert": "none",
                "on": false,
                "reachable": true
            },
            "swversion": "20200927",
            "type": "On/Off light",
            "uniqueid": "84:fd:27:ff:fe:3e:21:a4-01"
        }
    },
    "resourcelinks": {},
    "rules": {},
    "scenes": {},
    "schedules": {},
    "sensors": {
        "1": {
            "config": {
                "configured": true,
                "on": true,
                "sunriseoffset": 30,
                "sunsetoffset": -30
            },
            "etag": "115bbf1b2e3fda66da506f75a01dbd2a",
            "manufacturername": "Philips",
            "modelid": "PHDL00",
            "name": "Daylight",
            "state": {
                "dark": false,
                "daylight": true,
                "lastupdated": "2021-06-16T11:52:42.882",
                "status": 170,
                "sunrise": "2021-06-16T03:47:46",
                "sunset": "2021-06-16T19:57:28"
            },
            "swversion": "1.0",
            "type": "Daylight",
            "uniqueid": "00:21:2e:ff:ff:07:39:ce-01"
        },
        "2": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "aa11e0450f275be2cce090277c025fdc",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Salon",
            "state": {
                "lastupdated": "2021-06-16T12:55:51.413",
                "temperature": 2610
            },
            "swversion": "20201026",
            "type": "ZHATemperature",
            "uniqueid": "00:12:4b:00:23:20:97:a7-01-0402"
        },
        "3": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "86bcba0bf03caad10bdc42c15cf8b7cd",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Salon",
            "state": {
                "humidity": 6049,
                "lastupdated": "2021-06-16T12:54:43.080"
            },
            "swversion": "20201026",
            "type": "ZHAHumidity",
            "uniqueid": "00:12:4b:00:23:20:97:a7-01-0405"
        },
        "4": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "d4aaee3a94c1e1ef79d32489ca46ee30",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Bureau",
            "state": {
                "lastupdated": "2021-06-16T12:55:35.950",
                "temperature": 2612
            },
            "swversion": "20201026",
            "type": "ZHATemperature",
            "uniqueid": "00:12:4b:00:22:e9:6b:35-01-0402"
        },
        "5": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "d30f7088f91dc51e5740d41ef512e27d",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Bureau",
            "state": {
                "humidity": 5947,
                "lastupdated": "2021-06-16T12:51:26.679"
            },
            "swversion": "20201026",
            "type": "ZHAHumidity",
            "uniqueid": "00:12:4b:00:22:e9:6b:35-01-0405"
        },
        "6": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "591b3661757e9af5b96f3cfd40d8c13a",
            "lastseen": "2021-06-16T12:54Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Chambre",
            "state": {
                "lastupdated": "2021-06-16T12:48:08.111",
                "temperature": 2639
            },
            "swversion": "20201026",
            "type": "ZHATemperature",
            "uniqueid": "00:12:4b:00:22:cd:60:68-01-0402"
        },
        "7": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "3caf52ce5e47682918eb0a02220e911b",
            "lastseen": "2021-06-16T12:54Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Chambre",
            "state": {
                "humidity": 6024,
                "lastupdated": "2021-06-16T12:54:57.894"
            },
            "swversion": "20201026",
            "type": "ZHAHumidity",
            "uniqueid": "00:12:4b:00:22:cd:60:68-01-0405"
        },
        "9": {
            "config": {
                "battery": 100,
                "group": "4",
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "e2119183d012a4ce4f6c627164fa90f2",
            "lastseen": "2021-06-16T12:47Z",
            "manufacturername": "eWeLink",
            "mode": 1,
            "modelid": "WB01",
            "name": "Switch Mini",
            "state": {
                "buttonevent": null,
                "lastupdated": "none"
            },
            "swversion": "20201026",
            "type": "ZHASwitch",
            "uniqueid": "00:12:4b:00:22:ee:43:58-01-0006"
        }
    }
}

**Comment by marvin-SL** [comment] 2021-06-16 13:14
Same for me with the last update and pwabeta

Here's the log

`{
    "config": {
        "UTC": "2021-06-16T12:55:51",
        "announceinterval": 45,
        "announceurl": "https://phoscon.de/discover",
        "apiversion": "2.11.05",
        "bridgeid": "00212EFFFF0739CE",
        "datastoreversion": "93",
        "devicename": "ConBee II",
        "dhcp": true,
        "disablePermitJoinAutoOff": false,
        "discovery": true,
        "factorynew": false,
        "fwneedupdate": false,
        "fwupdatestate": "idle",
        "fwversion": "0x26660700",
        "gateway": "192.168.1.1",
        "groupdelay": 50,
        "homebridge": "not-available",
        "ipaddress": "192.168.1.39",
        "lightlastseeninterval": 60,
        "linkbutton": false,
        "localtime": "2021-06-16T14:55:51",
        "mac": "84:39:c0:0b:17:f3",
        "modelid": "deCONZ",
        "name": "Phoscon-GW",
        "netmask": "255.255.255.0",
        "networkopenduration": 180,
        "otauactive": false,
        "otaustate": "off",
        "panid": 31043,
        "permitjoin": 0,
        "permitjoinfull": 0,
        "port": 8080,
        "portalservices": false,
        "proxyaddress": "none",
        "proxyport": 0,
        "replacesbridgeid": null,
        "rfconnected": true,
        "runmode": "normal",
        "starterkitid": "",
        "swcommit": "ab7c379bbb582a6b0b9d4f5271d5bb36ddf8d3c0",
        "swupdate": {
            "notify": false,
            "text": "",
            "updatestate": 0,
            "url": "",
            "version": "2.11.05"
        },
        "swupdate2": {
            "autoinstall": {
                "on": false,
                "updatetime": ""
            },
            "bridge": {
                "lastinstall": "2021-05-17T16:24:11",
                "state": "noupdates"
            },
            "checkforupdate": false,
            "lastchange": "",
            "state": "noupdates"
        },
        "swversion": "2.11.05",
        "system": "other",
        "timeformat": "12h",
        "timezone": null,
        "updatechannel": "stable",
        "uuid": "c4f50f6c-51b4-4ddf-923d-d84222cfe01b",
        "websocketnotifyall": true,
        "websocketport": 443,
        "whitelist": {
            "1CD3CBEA04": {
                "create date": "2021-06-13T20:32:58",
                "last use date": "2021-06-15T21:46:41",
                "name": "Phoscon#B360x273"
            },
            "21A88E4457": {
                "create date": "2021-06-16T12:22:29",
                "last use date": "2021-06-16T12:52:31",
                "name": "Phoscon#B1280x597"
            },
            "4DBDCA536B": {
                "create date": "2021-06-15T10:56:12",
                "last use date": "2021-06-15T10:56:53",
                "name": "Phoscon#B360x315"
            },
            "5D5F40BCF6": {
                "create date": "2021-06-05T14:54:38",
                "last use date": "2021-06-05T14:54:41",
                "name": "Phoscon#B1366x645"
            },
            "98E23C2A29": {
                "create date": "2021-06-16T12:54:17",
                "last use date": "2021-06-16T12:55:51",
                "name": "Phoscon#B1280x597"
            }
        },
        "wifi": "not-available",
        "wifiavailable": [],
        "wifichannel": "1",
        "wificlientname": null,
        "wifiip": "192.168.8.1",
        "wifimgmt": 0,
        "wifiname": null,
        "wifitype": "accesspoint",
        "zigbeechannel": 15
    },
    "groups": {
        "2": {
            "action": {
                "alert": "none",
                "bri": 127,
                "colormode": "hs",
                "ct": 0,
                "effect": "none",
                "hue": 0,
                "on": true,
                "sat": 127,
                "scene": "1",
                "xy": [
                    0,
                    0
                ]
            },
            "devicemembership": [],
            "etag": "9178b312ecaf3b866e7931bf7ccefa71",
            "hidden": false,
            "id": "2",
            "lights": [
                "2"
            ],
            "lightsequence": [],
            "multideviceids": [],
            "name": "Salon",
            "scenes": [
                {
                    "id": "1",
                    "lightcount": 1,
                    "name": "Scène Lumière Salon",
                    "transitiontime": 0
                }
            ],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "LightGroup"
        },
        "4": {
            "action": {
                "alert": "none",
                "bri": 127,
                "colormode": "hs",
                "ct": 0,
                "effect": "none",
                "hue": 0,
                "on": false,
                "sat": 127,
                "scene": null,
                "xy": [
                    0,
                    0
                ]
            },
            "devicemembership": [
                "9"
            ],
            "etag": "5cea63e7094e97f13aa76dae6ad9f29b",
            "hidden": false,
            "id": "4",
            "lights": [],
            "lightsequence": [],
            "multideviceids": [],
            "name": "WB01 9",
            "scenes": [],
            "state": {
                "all_on": false,
                "any_on": false
            },
            "type": "LightGroup",
            "uniqueid": "00:12:4b:00:22:ee:43:58"
        }
    },
    "lights": {
        "1": {
            "etag": "0ccea6c41b542d107d40952d19ca7e59",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2021-06-16T12:54Z",
            "manufacturername": "dresden elektronik",
            "modelid": "ConBee II",
            "name": "Configuration tool 1",
            "state": {
                "reachable": true
            },
            "swversion": "0x26580700",
            "type": "Configuration tool",
            "uniqueid": "00:21:2e:ff:ff:07:39:ce-01"
        },
        "2": {
            "etag": "949e7c6abc3d7449c144c65de793da3a",
            "hascolor": false,
            "lastannounced": null,
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "SONOFF",
            "modelid": "01MINIZB",
            "name": "Lumière salon",
            "state": {
                "alert": "none",
                "on": false,
                "reachable": true
            },
            "swversion": "20200927",
            "type": "On/Off light",
            "uniqueid": "84:fd:27:ff:fe:3e:21:a4-01"
        }
    },
    "resourcelinks": {},
    "rules": {},
    "scenes": {},
    "schedules": {},
    "sensors": {
        "1": {
            "config": {
                "configured": true,
                "on": true,
                "sunriseoffset": 30,
                "sunsetoffset": -30
            },
            "etag": "115bbf1b2e3fda66da506f75a01dbd2a",
            "manufacturername": "Philips",
            "modelid": "PHDL00",
            "name": "Daylight",
            "state": {
                "dark": false,
                "daylight": true,
                "lastupdated": "2021-06-16T11:52:42.882",
                "status": 170,
                "sunrise": "2021-06-16T03:47:46",
                "sunset": "2021-06-16T19:57:28"
            },
            "swversion": "1.0",
            "type": "Daylight",
            "uniqueid": "00:21:2e:ff:ff:07:39:ce-01"
        },
        "2": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "aa11e0450f275be2cce090277c025fdc",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Salon",
            "state": {
                "lastupdated": "2021-06-16T12:55:51.413",
                "temperature": 2610
            },
            "swversion": "20201026",
            "type": "ZHATemperature",
            "uniqueid": "00:12:4b:00:23:20:97:a7-01-0402"
        },
        "3": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "86bcba0bf03caad10bdc42c15cf8b7cd",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Salon",
            "state": {
                "humidity": 6049,
                "lastupdated": "2021-06-16T12:54:43.080"
            },
            "swversion": "20201026",
            "type": "ZHAHumidity",
            "uniqueid": "00:12:4b:00:23:20:97:a7-01-0405"
        },
        "4": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "d4aaee3a94c1e1ef79d32489ca46ee30",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Bureau",
            "state": {
                "lastupdated": "2021-06-16T12:55:35.950",
                "temperature": 2612
            },
            "swversion": "20201026",
            "type": "ZHATemperature",
            "uniqueid": "00:12:4b:00:22:e9:6b:35-01-0402"
        },
        "5": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "d30f7088f91dc51e5740d41ef512e27d",
            "lastseen": "2021-06-16T12:55Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Bureau",
            "state": {
                "humidity": 5947,
                "lastupdated": "2021-06-16T12:51:26.679"
            },
            "swversion": "20201026",
            "type": "ZHAHumidity",
            "uniqueid": "00:12:4b:00:22:e9:6b:35-01-0405"
        },
        "6": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "591b3661757e9af5b96f3cfd40d8c13a",
            "lastseen": "2021-06-16T12:54Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Chambre",
            "state": {
                "lastupdated": "2021-06-16T12:48:08.111",
                "temperature": 2639
            },
            "swversion": "20201026",
            "type": "ZHATemperature",
            "uniqueid": "00:12:4b:00:22:cd:60:68-01-0402"
        },
        "7": {
            "config": {
                "battery": 100,
                "offset": 0,
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "3caf52ce5e47682918eb0a02220e911b",
            "lastseen": "2021-06-16T12:54Z",
            "manufacturername": "eWeLink",
            "modelid": "TH01",
            "name": "Chambre",
            "state": {
                "humidity": 6024,
                "lastupdated": "2021-06-16T12:54:57.894"
            },
            "swversion": "20201026",
            "type": "ZHAHumidity",
            "uniqueid": "00:12:4b:00:22:cd:60:68-01-0405"
        },
        "9": {
            "config": {
                "battery": 100,
                "group": "4",
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "e2119183d012a4ce4f6c627164fa90f2",
            "lastseen": "2021-06-16T12:47Z",
            "manufacturername": "eWeLink",
            "mode": 1,
            "modelid": "WB01",
            "name": "Switch Mini",
            "state": {
                "buttonevent": null,
                "lastupdated": "none"
            },
            "swversion": "20201026",
            "type": "ZHASwitch",
            "uniqueid": "00:12:4b:00:22:ee:43:58-01-0006"
        }
    }
}`

**Comment by SEK-DE** [comment] 2021-06-17 11:50
![Filter](https://user-images.githubusercontent.com/80257288/122391090-f34c0900-cf72-11eb-9579-fee0fdfce936.PNG)
Please use the filter and copy only the log from this sensor, thx.

**Comment by SEK-DE** [comment] 2021-06-17 13:06
Ah ok, it was a missunderstanding between me an one of our programmer. The "long press" function shows up with only one event, what makes it hard to set, for example, as a dimming event. Becouse the event only shows up if you stop press the button. To get to the point, we wont implement any support for this kind of long press function. Sorry guys.

**Comment by bmalynovytch** [comment] 2021-06-18 06:50
@SEK-DE why have you closed the issue ?

The issue isn't related to long press, the whole button isn't showing at all. Please reopen.

**Comment by SEK-DE** [comment] 2021-06-18 07:41
@bmalynovytch i closed this because we cant reproduce your issue.
I integrate the switch to different setups, with different deCONZ versions and different Firmware Versions, and it works every single time at the first try. 
The API Info says:

                    {
    "config": {
        "battery": 100,
        "group": "2",
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "72d5ebaef4acfbd6e06fde2bd1f02db6",
    "lastseen": "2021-06-18T08:32Z",
    "manufacturername": "eWeLink",
    "mode": 1,
    "modelid": "WB01",
    "name": "Schalter Mini",
    "state": {
        "buttonevent": 1002,
        "lastupdated": "2021-06-18T08:32:57.336"
    },
    "swversion": "20200718",
    "type": "ZHASwitch",
    "uniqueid": "00:12:4b:00:22:42:49:02-01-0006"
}

It also shows up correct in deCONZ.
So if you cant integrate the device at all, it´s maybe broken.

**Comment by SEK-DE** [comment] 2021-06-18 08:09
@bmalynovytch please answer me to the following questions, maybe the problem is somewhere else:

1. host system (Raspberry Pi 3B+ / 4B / PC / NAS):
   Response: 
2. execution method (Raspbian / Ubuntu / Home Assistant deCONZ add-on / Marthoc Docker container / Windows / Virtual Machine):
   Response:
3. firmware version (format 26xxyy00):
   Response:
4. deCONZ Version (Format 2.xx.yy):
   Response: 
5. device (ConBee I / ConBee II / RaspBee I / RaspBee II):
   Response:
6. is the ConBee I / II connected to a USB 2.0 or USB 3.0 (blue) socket? - only relevant for ConBee I/II:
   Answer:
7. is a USB extension used?   (yes / no) - only relevant for ConBee I/II:
   Answer:
8. are other USB or serial devices connected to the host system? (yes / no) - If yes: which ones?):
   Answer:
9. if Raspberry Pi: which power supply is used? (original / manufacturer + model) + specify volts and amps: (e.g. 5.0V, 1.0A):
   Answer:
10. if Raspberry Pi: On which image base is the system set up?: (Phoscon / Raspbian / Raspberry Pi OS / Home Assistant ...):
    Answer:
11. if Raspberry Pi: Which way was deCONZ installed? (APT repository / dpkg / via a plug-in).
    Response:

**Comment by senilio** [comment] 2021-06-18 08:38
It seems there's a misunderstanding somewhere 🙂. The switch works great on all fronts, the problem is that the device is not visible in the Phoscon switch editor, which makes it impossible to create rules from Phoscon using buttonevents from this switch as a condition. Please see the first post.

It is possible to create rules using REST API.

**Comment by SEK-DE** [comment] 2021-06-18 08:47
![Sonoff](https://user-images.githubusercontent.com/80257288/122533794-387b4400-d022-11eb-9e48-92c94b8f93ad.PNG)
That´s how it looks for me. So using the switch editor is possible at least. I hope i get you right this time 😅 
I´m using 2.12.01 and 26690700 over here.

**Comment by senilio** [comment] 2021-06-18 08:59
I will admit I haven't looked at this since I created the issue back in January, I just commented to try and clarify the original issue :)

I checked this now, and you are indeed correct it IS visible in the 2.12.01 Phoscon, and all looks good to me 👍

![Screenshot 2021-06-18 at 10 54 12](https://user-images.githubusercontent.com/7874309/122535271-ad9b4900-d023-11eb-8eac-6477f427237f.png)
![Screenshot 2021-06-18 at 10 54 20](https://user-images.githubusercontent.com/7874309/122535278-af650c80-d023-11eb-8d4b-e0dffb2d6904.png)

Before the switch was not even visible in the list of available switches. 

@bmalynovytch Make sure to update to 2.12.01 and retry.

**Comment by bmalynovytch** [comment] 2021-06-28 06:51
I gave a quick look with the beta GUI and can confirm the buttons are now usable in the interface to be grouped.
/close

**Closed** 2021-06-28 12:27 UTC
